from .vars import *

rules = [
    # Dry Terrain, Wheel
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['low'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['low'] & speed['medium'], mobility['mediumhigh']),
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['low'] & speed['high'], mobility['high']),
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['medium'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['medium'] & speed['medium'], mobility['mediumhigh']),
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['medium'] & speed['high'], mobility['high']),
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['high'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['high'] & speed['medium'], mobility['mediumhigh']),
    ctrl.Rule(terrain['dry'] & vehicle['wheel'] & weight['high'] & speed['high'], mobility['high']),
    # Dry Terrain, Track
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['low'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['low'] & speed['medium'], mobility['medium']),
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['low'] & speed['high'], mobility['mediumhigh']),
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['medium'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['medium'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['medium'] & speed['high'], mobility['medium']),
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['high'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['high'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['dry'] & vehicle['track'] & weight['high'] & speed['high'], mobility['mediumlow']),
    # Wet Terrain, Wheel
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['low'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['low'] & speed['medium'], mobility['medium']),
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['low'] & speed['high'], mobility['mediumhigh']),
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['medium'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['medium'] & speed['medium'], mobility['mediumhigh']),
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['medium'] & speed['high'], mobility['mediumhigh']),
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['high'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['high'] & speed['medium'], mobility['medium']),
    ctrl.Rule(terrain['wet'] & vehicle['wheel'] & weight['high'] & speed['high'], mobility['mediumhigh']),
    # Wet Terrain, Track
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['low'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['low'] & speed['medium'], mobility['mediumhigh']),
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['low'] & speed['high'], mobility['mediumhigh']),
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['medium'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['medium'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['medium'] & speed['high'], mobility['medium']),
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['high'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['high'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['wet'] & vehicle['track'] & weight['high'] & speed['high'], mobility['medium']),
    # Snow Terrain, Wheel
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['low'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['low'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['low'] & speed['high'], mobility['medium']),
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['medium'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['medium'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['medium'] & speed['high'], mobility['medium']),
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['high'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['high'] & speed['medium'], mobility['medium']),
    ctrl.Rule(terrain['snow'] & vehicle['wheel'] & weight['high'] & speed['high'], mobility['mediumhigh']),
    # Snow Terrain, Track
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['low'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['low'] & speed['medium'], mobility['medium']),
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['low'] & speed['high'], mobility['mediumhigh']),
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['medium'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['medium'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['medium'] & speed['high'], mobility['medium']),
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['high'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['high'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['snow'] & vehicle['track'] & weight['high'] & speed['high'], mobility['mediumlow']),
    # Sand Terrain, Wheel
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['low'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['low'] & speed['medium'], mobility['medium']),
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['low'] & speed['high'], mobility['mediumhigh']),
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['medium'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['medium'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['medium'] & speed['high'], mobility['medium']),
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['high'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['high'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['sand'] & vehicle['wheel'] & weight['high'] & speed['high'], mobility['medium']),
    # Sand Terrain, Track
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['low'] & speed['low'], mobility['mediumlow']),
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['low'] & speed['medium'], mobility['medium']),
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['low'] & speed['high'], mobility['mediumhigh']),
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['medium'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['medium'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['medium'] & speed['high'], mobility['medium']),
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['high'] & speed['low'], mobility['low']),
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['high'] & speed['medium'], mobility['mediumlow']),
    ctrl.Rule(terrain['sand'] & vehicle['track'] & weight['high'] & speed['high'], mobility['mediumlow']),
]
